[env:manual]
platform = native
lib_deps = reinodovo/BombManualGenerator@0.3.0
           file://../rules
build_unflags = -std=gnu++11
build_flags = -std=gnu++17
              !command -v bomb >/dev/null 2>&1 && bomb pio-build-flags manual || true
