; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[env:development]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
lib_deps = file://../../bomb-protocol
           file://../rules
lib_ignore = WebServer
build_unflags = -std=gnu++11
build_flags = -std=gnu++17 -DDEBUG=true -DBAUD_RATE=115200

[env:release]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps = reinodovo/BombProtocol@0.4.1
           file://../rules
lib_ignore = WebServer
build_unflags = -std=gnu++11
build_flags = -std=gnu++17
