[env:development]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps = file://../../bomb-protocol
           file://../rules
build_unflags = -std=gnu++11
build_flags = -std=gnu++17 -DDEBUG=true
              !command -v bomb >/dev/null 2>&1 && bomb pio-build-flags firmware --dev || true

[env:release]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps = reinodovo/BombProtocol@0.6.0
           file://../rules
build_unflags = -std=gnu++11
build_flags = -std=gnu++17
              !command -v bomb >/dev/null 2>&1 && bomb pio-build-flags firmware || true
